Feature/fr 33
FridayRelease/1game pull request #12
Opened 2023-04-01 15:05 UTC by DivoDivnoe

### Какую задачу решаем
Вёрстка страниц профиля, редактирования профиля и пароля, формы замены аватарки, страницы с окончанием игры.

### Скриншоты/видяшка (если есть)
![Screenshot 2023-04-01 at 17 56 36](https://user-images.githubusercontent.com/20484165/229296949-4e607734-f391-4d98-a0e5-58002b06d1bd.png)
![Screenshot 2023-04-01 at 17 56 53](https://user-images.githubusercontent.com/20484165/229296951-877c5468-ff92-4c18-92bb-7068030a773c.png)
 ![Screenshot 2023-04-01 at 18 02 09](https://user-images.githubusercontent.com/20484165/229297015-85bc3f98-aae4-4a6e-a8b5-e3449e9a6e0c.png)
![Screenshot 2023-04-01 at 18 04 26](https://user-images.githubusercontent.com/20484165/229297131-6de71b14-626e-4d50-9296-0e4b995f9ce0.png)

### TBD (если есть)

2023-04-02 11:18 UTC, pellexa commented
Мощно! Все посмотрел, но не все осознал.

2023-04-02 21:36 UTC, timerbayevaf requested changes

2023-04-02 21:36 UTC, timerbayevaf commented on packages/client/src/controllers/user-controllers.ts
> +    description: 'Попробуйте обновить аватар еще раз',
копипаст ошибки

2023-04-02 21:36 UTC, timerbayevaf commented on packages/client/src/api/user.ts
> +    return await this.http.put('/user/password', data);
не критично, но можно добавить тип `StatusResponse`, чтобы в `controllers` можно было проверить по ответу с бэка, а не по статусу ( в случае изменения апи `например ошибка будет приходить со статусом 200`, можно будет увидеть ошибку)

2023-04-02 21:36 UTC, timerbayevaf commented on packages/client/src/components/avatar/avatar.tsx
> +  const src = `${import.meta.env.VITE_AUTH_API}resources${avatar}`;
думаю лучше перенести в контроллер все логику с получением аватара.

Например в случае, если аватар будет использоваться в нескольких компонентах и `url` изображения будет отличаться, придется добавлять еще логику, компонент Аватар не должен отвечать за то, где находится аватар.

например так
`const blobAvatar = get(`resources/${path}`, {
        responseType: 'blob',
      });
 const avatar = URL.createObjectURL(blob);
`

2023-04-02 21:36 UTC, timerbayevaf commented on packages/client/src/pages/edit-password/edit-password.interface.ts
нужен ли пустой файл?

2023-04-02 21:36 UTC, timerbayevaf commented on packages/client/src/pages/edit-profile/edit-profile.interface.ts
нужен ли этот пустой файл?

2023-04-02 21:47 UTC, timerbayevaf commented
все отлично) все работает) 
Единственное есть вопрос по поводу контроллером и сагой, где будет какая логика.
Я предполагал, что контроллер будет отвечать только за получение данных и модификацию этих данных.
Например, получение данных и его обогащение другой информацией, например аватара
Или после авторизации, получить данные пользователя. Т.е контроллер будет отвечать только за получение информации и сопутствующие преобразования данных

А в сагах будет логика связанная с тем, что делать дальше с этой информацией, например переправить пользователя на другую страницу.

2023-04-03 10:10 UTC, shoom1337-yt requested changes

2023-04-03 10:10 UTC, shoom1337-yt commented on packages/client/src/components/profile/menu/menu.tsx
> +        disabled={disabled ?? state === MenuState.ERROR}
❓ Все вычисления нужно вынести из разметки в переменные, чтобы получилось, примерно так:
```
className={buttonClassName}
type={buttonType}
disabled={isButtonDisabled}
```
Будет более наглядно и читаемо.

2023-04-03 10:10 UTC, shoom1337-yt commented on packages/client/src/controllers/user-controllers.ts
> +    description: 'Попробуйте обновить аватар еще раз',
Поддерживаю) 
Можно вынести на один уровень со всеми методами.

2023-04-03 10:10 UTC, shoom1337-yt commented on packages/client/src/pages/game-over/game-over.scss
> +    font-family: Joystix;
ℹ️ Хорошо бы добавить как фоллбэк системный шрифт. Например, 'sans-serif'.

2023-04-03 18:26 UTC, DivoDivnoe commented on packages/client/src/api/http-client.ts
> +      return axios.put(`${this.prefixUrl}${url}`, data, {
Не получилось поменять Content-Type при использовании инстанса. Хотя, вот сейчас вспомнил, что передавал файл вместо formdata, скорее всего поэтому и не работало. ща еще попробую

2023-04-03 18:53 UTC, DivoDivnoe commented
> все отлично) все работает) Единственное есть вопрос по поводу контроллером и сагой, где будет какая логика. Я предполагал, что контроллер будет отвечать только за получение данных и модификацию этих данных. Например, получение данных и его обогащение другой информацией, например аватара Или после авторизации, получить данные пользователя. Т.е контроллер будет отвечать только за получение информации и сопутствующие преобразования данных
> 
> А в сагах будет логика связанная с тем, что делать дальше с этой информацией, например переправить пользователя на другую страницу.

Я с сагами пока не очень, сделал как мне понятно на данный момент, по аналогии с предыдущим проектом, когда мы получаем данные и обновляем стейт в контроллере. А это вообще распространенная практика, когда редьюсер ничего не делает, а стейт обновляется в сагах?

2023-04-03 20:48 UTC, DivoDivnoe commented
Исправил замечания!

2023-04-04 06:47 UTC, shoom1337-yt approved these changes

2023-04-05 16:50 UTC, merged