Feature/fr 31
FridayRelease/1game pull request #13
Opened 2023-04-02 14:01 UTC by pellexa

### Какую задачу решаем
Вёрстка страницы лидерборда.

### Скриншоты/видяшка (если есть)
![leaderboard](https://user-images.githubusercontent.com/34819049/229357671-ce2054af-9533-4c58-8bcf-c0cf238acdf1.png)

### TBD (если есть)

2023-04-02 16:11 UTC, DivoDivnoe commented on packages/client/src/components/position/position.tsx
> +};
По идее, содержимое можно как-то вот так сократить:

```
const color = ['gold', 'silver', 'bronze'][position - 1];
const content = color ? <IconCrown fillColor={`var(--${color})`} /> : position;

return <div className={className}>{content}</div>;

2023-04-02 22:02 UTC, timerbayevaf requested changes

2023-04-02 22:02 UTC, timerbayevaf commented on packages/client/src/components/icons/crown/crown.tsx
> +  return (
Можно лучше) 
лучше использовать свг отдельным файлов с расширением свг и импортировать его

Если свг будет большого объема или большое количество свг, то бандл проекта увеличиться на его размер
как импортировать отдельно свг, можно почитать тут
https://www.freecodecamp.org/news/how-to-import-svgs-in-react-and-vite/

2023-04-02 22:02 UTC, timerbayevaf commented on packages/client/src/components/leaderboard-list/leaderboard-list.tsx
> +// import { LeaderboardListProps } from './types';
лучше удалить неинформативный комментарий

2023-04-03 05:30 UTC, pellexa commented on packages/client/src/app.scss
> +  --gold: #ffd700;
Выше Андрей написал как сократить код, там используются:
`const color = ['gold', 'silver', 'bronze'][position - 1];`

2023-04-03 10:15 UTC, shoom1337-yt requested changes

2023-04-03 10:15 UTC, shoom1337-yt commented on packages/client/src/components/position/position.tsx
> +  const content = color ? <IconCrown fill={`var(--${color})`} /> : position;
🚀 Интересная логика вычисления иконки!

2023-04-03 10:15 UTC, shoom1337-yt commented on packages/client/src/pages/leaderboard/leaderboard.scss
> +    font: 400 30px/1 'Joystix';
❓ Название шрифта лучше вынести в переменную и здесь переопределить свойство `font-family`. А то хардкодится в нескольких местах.

2023-04-03 11:16 UTC, pellexa commented on packages/client/src/components/position/position.tsx
> +  const content = color ? <IconCrown fill={`var(--${color})`} /> : position;
Спасибо @DivoDivnoe за эту краткую реализацию.

2023-04-03 11:26 UTC, shoom1337-yt approved these changes

2023-04-05 16:45 UTC, timerbayevaf approved these changes

2023-04-05 20:22 UTC, merged