Feature/fr 24
FridayRelease/1game pull request #15
Opened 2023-04-05 22:20 UTC by pellexa

### Какую задачу решаем
Домашняя страница.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-10 16:17 UTC, shoom1337-yt requested changes

2023-04-10 16:17 UTC, shoom1337-yt commented on packages/client/src/app.tsx
> +      localStorage.setItem('theme', JSON.stringify({ value: stateTheme.value }));
ℹ️ Для удобства, стоит сделать утилиту, которая будет получать название ключа и значение и сетить в хранилище. Будет более читаемо и можно переиспользовать в других местах приложения, если понадобится.

2023-04-10 16:17 UTC, shoom1337-yt commented on packages/client/src/app.tsx
> +      const theme = JSON.parse(localStorage.getItem('theme') || '{}');
❓ Дублируется в этом же файле.
В целом, всю логику смены темы можно вынести в хук, а здесь оставить только useEffect с навешиванием события.

2023-04-10 16:17 UTC, shoom1337-yt commented on packages/client/src/components/error/error.scss
> +      color: var(--main-bg-alert);
🚀 Правильно, все цвета — в переменные 🙂

2023-04-10 16:17 UTC, shoom1337-yt commented on packages/client/src/pages/home/home.tsx
> +            </Link>
❓ Тут получился копипаст, который плохо читается и поддерживается. Давай вынесем данные в массив links. И отрендерим навигацию циклом:
```
{links.map((link) => <Link to={link.url}... />}
```
Получится короче и понятнее.

2023-04-10 16:17 UTC, shoom1337-yt commented on packages/client/src/store/slices/theme-slice.ts
> +      state.value = state.isLightTheme ? 'light' : 'dark';
❓ А для чего переменная `isLightTheme`? Получается какое-то дублирование? В стейте и флаг, и прямое указание light/dark.
Что будет, если третью тему захотим добавить? Не поломается логика?

2023-04-11 11:37 UTC, pellexa commented on packages/client/src/pages/home/home.tsx
> +            </Link>
Получается так, разве это лучше читается? А если в children, кроме иконок, добавятся другие элементы, то им нужно будет ещё дополнительно придумывать значение атрибута key и поддерживать его. 
 
```javascript
  const links = [
    {
      id: 'профиль',
      url: ProfileUrl,
      classes: ['home__link', 'home__link__bg-green'],
      children: <IconProfile className="home__link-icon" fill="var(--main-color-bg)" />,
    },
    {
      id: 'доска лидеров',
      url: LeaderboardUrl,
      classes: ['home__link', 'home__link__bg-green'],
      children: <IconTrophy className="home__link-icon" stroke="var(--main-color-bg)" />,
    },
    {
      id: 'форум',
      url: ForumUrl,
      classes: ['home__link', 'home__link__bg-green'],
      children: <IconForum className="home__link-icon" stroke="var(--main-color-bg)" />,
    },
    {
      id: 'выйти',
      url: '#',
      classes: ['home__link', 'home__link__bg-green'],
      children: <IconLogout className="home__link-icon" fill="var(--main-color-bg)" />,
    },
    { id: 'старт', url: '#', classes: ['home__link', 'home__link-start', 'home__link__bg-red'] },
  ];

  const listItems = links.map(link => (
    <Link to={link.url} className={cn(link.classes)} key={link.id}>
      {link.children}
      {link.id}
    </Link>
  ));

... 

<nav className="home__nav">{listItems}</nav>
```

2023-04-11 12:42 UTC, pellexa commented on packages/client/src/store/slices/theme-slice.ts
> +      state.value = state.isLightTheme ? 'light' : 'dark';
Добавление третьей темы не предусмотрено.
isLigthTheme нужен для контроля атрибута checked (в поле input)

2023-04-11 15:11 UTC, shoom1337-yt commented on packages/client/src/pages/home/home.tsx
> +            </Link>
Как будет время, попробуй реализовать. Или напиши в Пачке, вместе сделаем)

2023-04-11 15:11 UTC, shoom1337-yt approved these changes

2023-04-11 15:12 UTC, merged