Валидация форм
FridayRelease/1game pull request #18
Opened 2023-04-13 07:46 UTC by vvozvv

### Какую задачу решаем
Валидация форм

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-14 09:14 UTC, shoom1337-yt requested changes
Вынеси, пожалуйста, сообщения ошибок при валидации в константы.

2023-04-14 09:14 UTC, shoom1337-yt commented on packages/client/src/features/authentication/hooks/use-validate.ts
> +  validationSchema?: InferType<any>;
ℹ️ Решение на грани)
Поскольку, у нас учебный проект, не буду блочить в этом случае весь ПР. Но, когда выдастся время, посмотри, пожалуйста, как можно обойтись без `any`.

2023-04-15 11:46 UTC, shoom1337-yt approved these changes

2023-04-16 10:22 UTC, timerbayevaf approved these changes

2023-04-18 11:20 UTC, closed without merging