Какую задачу решаем
FridayRelease/1game pull request #20
Opened 2023-04-14 15:06 UTC by Dmitryra27

Добавление Service Worker

Было реализовано:

в app.tsx регистрация Service Worker, использование с fetch для асинхронного получения данных внутри хука useEffect

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-17 10:16 UTC, shoom1337-yt requested changes

2023-04-17 10:16 UTC, shoom1337-yt commented on packages/client/src/service-worker/asset.js
Сюда позже добавятся ресурсы для кеширования?

2023-04-17 10:16 UTC, shoom1337-yt commented on packages/client/src/app.tsx
> +        const url = `http://localhost:3001`;
❓ Всё же, порт лучше из окружения брать. Да и сам урл тоже можно в энв вынести.

2023-04-17 10:16 UTC, shoom1337-yt commented on .DS_Store
❓ Вот эту штуку давай пофиксим заодно: https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

2023-04-18 12:46 UTC, Dmitryra27 commented on packages/client/src/service-worker/asset.js
да, так и будет

2023-04-18 12:54 UTC, Dmitryra27 commented on packages/client/src/app.tsx
> +        const url = `http://localhost:3001`;
исправил

2023-04-18 12:57 UTC, Dmitryra27 commented on .DS_Store
исправил вроде бы

2023-04-18 19:52 UTC, pellexa commented
Дима, я могу ошибаться но это жестокий копи-паст. Нужно побольше инфы почитать.

2023-04-19 04:37 UTC, shoom1337-yt approved these changes

2023-05-28 19:39 UTC, timerbayevaf commented
актуальная задача под `Service Worker`
https://github.com/FridayRelease/1game/pull/25

2023-05-28 19:39 UTC, closed without merging