Feature/fr 57
FridayRelease/1game pull request #35
Opened 2023-05-23 17:41 UTC by Dmitryra27

### Какую задачу решаем
Сделано API , Контролер для Leaderboard, доработаны компоненты, данные записываются на Сервер, в Стор, выводятся на страницу Лидеров

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-24 08:17 UTC, shoom1337-yt requested changes

2023-05-24 08:17 UTC, shoom1337-yt commented on packages/client/src/api/lider.ts
> +  add_user_to_leaderboard = async (data: ILeaderboardAddUser) => {
❓ Не критично, но всё же: это же JS-ный метод, почему не addUserToLeaderboard? 🙂

2023-05-24 08:17 UTC, shoom1337-yt commented on packages/client/src/controllers/lider-controller.ts
> +  }
❓ try

2023-05-24 08:17 UTC, shoom1337-yt commented on packages/client/src/controllers/lider-controller.ts
> +  throw new Error('Произошла ошибка при добавлении пользователя');
❓ catch

 try/catch в этом случае будет более читаемо и не понадобится `if (data === 'OK')`

2023-05-24 08:17 UTC, shoom1337-yt commented on packages/client/src/features/game/hooks/use-start.ts
> +          }
Ага, try/catch увидел, но в самом `addUserDatasToServer` это будет выглядеть более логично, на мой взгляд.

2023-05-24 08:55 UTC, pellexa requested changes

2023-05-24 08:55 UTC, pellexa commented on packages/client/src/api/types.ts
> -  type ITriggersDTO,
Зачем это удалил? Появилось пара новых ts-ошибок:

```
src/features/game/loaders/level.ts:50:18 - error TS2339: Property 'triggers' does not exist on type 'ILevelDTO'.

50   if (!levelSpec.triggers) {
                    ~~~~~~~~

src/features/game/loaders/level.ts:54:39 - error TS2339: Property 'triggers' does not exist on type 'ILevelDTO'.

54   for (const triggerSpec of levelSpec.triggers) {

```

2023-05-24 08:55 UTC, pellexa commented on packages/client/src/controllers/game-controllers.ts
> +    //@ts-ignore
Этот ts-ignore нужно убрать

2023-05-24 08:55 UTC, pellexa commented on packages/client/src/store/slices/leaderboard-slice.ts
> +  { name: 'Petr', score: 40 },
и здесь формата нет, выполни yarn format

2023-05-24 19:02 UTC, Dmitryra27 commented on packages/client/src/api/lider.ts
> +  add_user_to_leaderboard = async (data: ILeaderboardAddUser) => {
согласен

2023-05-24 19:03 UTC, Dmitryra27 commented on packages/client/src/controllers/lider-controller.ts
> +  }
Ok

2023-05-24 19:04 UTC, Dmitryra27 commented on packages/client/src/controllers/lider-controller.ts
> +  throw new Error('Произошла ошибка при добавлении пользователя');
Ok

2023-05-24 19:06 UTC, Dmitryra27 commented on packages/client/src/controllers/game-controllers.ts
> +    //@ts-ignore
убрал

2023-05-24 19:08 UTC, Dmitryra27 commented on packages/client/src/api/types.ts
> -  type ITriggersDTO,
поставил обратно, в том числе определение типа, хотя судя по всему не я удалял, а удалилось при обновлении

2023-05-24 19:24 UTC, Dmitryra27 commented on packages/client/src/store/slices/leaderboard-slice.ts
> +  { name: 'Petr', score: 40 },
согласен - убрал моковые данные, формат сделал везде, отдельно закоммитил

2023-05-24 19:28 UTC, Dmitryra27 commented on packages/client/src/controllers/game-controllers.ts
> +    //@ts-ignore
висит ошибка - TS2551: Property 'patternSheet' does not exist on type 'ILevelDTO'. Did you mean 'patterns'? - не я делал - не знаю как исправить

2023-05-24 19:36 UTC, Dmitryra27 commented on packages/client/src/features/game/hooks/use-start.ts
> +          }
исправил

2023-05-25 05:24 UTC, shoom1337-yt commented on packages/client/src/controllers/game-controllers.ts
> +    //@ts-ignore
В таком случае, можно задачу создать на доске и сюда комментарием закинуть TODO.

2023-05-25 05:24 UTC, shoom1337-yt approved these changes

2023-05-25 10:31 UTC, Dmitryra27 commented on packages/client/src/controllers/game-controllers.ts
> +    //@ts-ignore
Исправил!

2023-05-25 10:33 UTC, pellexa approved these changes

2023-05-25 10:35 UTC, merged