Feature/fr 77
FridayRelease/1game pull request #47
Opened 2023-06-01 10:02 UTC by Dmitryra27

### Какую задачу решаем
Реализация фронтенда форума

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-01 16:25 UTC, shoom1337-yt requested changes
Код выглядит рабочим, но сырым.
Много закомментированных строчек, console.log, ts-ignore, any. И периодически "пляшет" форматирование кода.
Если есть возможность, поправь, пожалуйста.

2023-06-01 16:25 UTC, shoom1337-yt commented on packages/client/src/api/types.ts
> +  comments?:[]|IComment[]|null,
❓ А почему тут может быть пустой массив, если есть описанный интерфейс для комментариев?

2023-06-01 16:25 UTC, shoom1337-yt commented on packages/client/src/controllers/forum-topic-controller.ts
> +  let data:any;
❓ В соседних методах переменная `data` инициализируется деструктуризацией из ответа. Здесь так же не получится?

2023-06-01 16:25 UTC, shoom1337-yt commented on packages/client/src/features/forum-topic/components/friends-left.tsx
> +            {list.map(( li : any, index: number) => (
❓ Давай здесь перепишем вот так: `list.map(( { avatar, display_name }, index: number)`. Избавимся от опасного `any`.

2023-06-01 16:25 UTC, shoom1337-yt commented on packages/client/src/features/forum-topic/components/header-user-right.tsx
> +            const name1 = res.display_name!==null ? res.display_name : res.first_name
`const name1 = res.display_name || res.first_name;`
Так не получится?

2023-06-02 04:26 UTC, Dmitryra27 commented on packages/client/src/api/types.ts
> +  comments?:[]|IComment[]|null,
согласен - исправил

2023-06-02 04:29 UTC, Dmitryra27 commented on packages/client/src/api/forum.ts
> +  // app.delete('/api/v1/topics/:id', [topicDelete]);
исправил

2023-06-02 04:29 UTC, Dmitryra27 commented on packages/client/src/api/forum.ts
> +  // app.delete('/api/v1/topics/:id', [topicDelete]);
сделал форматирование кода

2023-06-02 04:31 UTC, Dmitryra27 commented on packages/client/src/features/forum-topic/components/friends-left.tsx
> +            {list.map(( li : any, index: number) => (
согласен - исправил

2023-06-02 04:32 UTC, Dmitryra27 commented on packages/client/src/features/forum-topic/components/header-user-right.tsx
> +            const name1 = res.display_name!==null ? res.display_name : res.first_name
согласен

2023-06-02 04:42 UTC, Dmitryra27 commented on packages/client/src/features/forum/components/forum-header-user.tsx
> +            const avatar1 = res.avatar !== null ? 'https://ya-praktikum.tech/api/v2/resources/' + res.avatar : ''
вынес в константы

2023-06-02 04:46 UTC, Dmitryra27 commented on packages/client/src/features/forum/components/forum-title.tsx
> +                <label className="white">ОРУМ</label>
спасибо - запомню - исправил

2023-06-02 04:48 UTC, Dmitryra27 commented on packages/client/src/controllers/forum-topic-controller.ts
> +  let data:any;
исправил

2023-06-02 07:15 UTC, shoom1337-yt approved these changes

2023-06-02 22:53 UTC, timerbayevaf requested changes

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/constant/url_resources.ts
у нас настроен прокси, и следовательно нет необходимости где-то в файле писать обращение к АПИ яндекса
вместо этого следует в апи функцию `resources`

`async resources(img: string) {
    return await this.http.get('/resources/${img}');
  }`

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/constant/url_resources.ts
т.е мы обращаемся по адресу `/api/v2` и он переадресовывается на апи яндекса 
реализацию можно увидеть в файле proxy.middleware.ts

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/controllers/forum-comments-controller.ts
> +//export const setForumDatasToStore = (data: ITopic[], dispatch: Dispatch<AnyAction>) => {
не информативные/не используемые комментарии можно удалить

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/features/forum-topic/components/create-message.tsx
> +        addToServer(data).then(res => console.log('addToServer result = ', res));
для чего необходима эта функция `addToServer`
`addCommentToServer(data)`  почему нельзя обойтись вызовом этой функции

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/features/forum-topic/components/create-message.tsx
> +        await addCommentToServer(data).then(res => console.log('res = ', res));
console.log стоит использовать только при разработке, при реализации кода в прод, все эти функции стоит удалить

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/features/forum-topic/components/friends-left.tsx
> +        dispatch(ForumActions.setUsersFromServerToStore(response.data));
зачем тут инициализация `list` и сохранение в `store` посредством вызова функции `setUsersFromServerToStore`

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/features/forum/components/forum-topic-list.tsx
> +  }, [init_state]);
вообще не понятно, зачем тут это надо `init_state`
тут очень интересная логика, useEffect ожидает изменения состояния из селектора `ForumSelectors.topics` а дальше в цикле кружимся в запросе получаем данные и устанавливаем `setTopicsFromServerToStore` в стор и опять меняется `init_state` и так далее

2023-06-02 22:53 UTC, timerbayevaf commented on packages/client/src/features/forum/components/forum-topic-list.tsx
> +  }, [init_state]);
<img width="635" alt="image" src="https://github.com/FridayRelease/1game/assets/121462196/3a609233-dee1-4be0-91fa-c533e3920b93">

2023-06-04 11:12 UTC, Dmitryra27 commented on packages/client/src/constant/url_resources.ts
спасибо, исправил

2023-06-04 11:12 UTC, Dmitryra27 commented on packages/client/src/controllers/forum-comments-controller.ts
> +//export const setForumDatasToStore = (data: ITopic[], dispatch: Dispatch<AnyAction>) => {
ок

2023-06-04 11:17 UTC, Dmitryra27 commented on packages/client/src/features/forum-topic/components/create-message.tsx
> +        addToServer(data).then(res => console.log('addToServer result = ', res));
Согласен, исправил

2023-06-04 11:18 UTC, Dmitryra27 commented on packages/client/src/features/forum-topic/components/create-message.tsx
> +        await addCommentToServer(data).then(res => console.log('res = ', res));
удалил функциюaddToServer

2023-06-15 08:09 UTC, Dmitryra27 commented on packages/client/src/features/forum/components/forum-topic-list.tsx
> +  }, [init_state]);
исправил, сделал по другому

2023-06-22 13:10 UTC, closed without merging