Полноэкранный режим
FridayRelease/1game pull request #54
Opened 2023-06-16 15:24 UTC by vvozvv

### Какую задачу решаем
Фуллскрин апи

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-17 10:27 UTC, shoom1337-yt requested changes

2023-06-17 10:27 UTC, shoom1337-yt commented on packages/client/src/components/fullsreen-button/fullscreen-button.tsx
> +  const [isFullscreen, setFullscreen] = useState(false);
❓ Этот хук лучше положить в `useFullscreen`.

2023-06-17 10:27 UTC, shoom1337-yt commented on packages/client/src/components/fullsreen-button/fullscreen-button.tsx
> +  const { activateFullscreen, deactivateFullscreen } = useFullscreen();
❓ А здесь доставать значение `isFullscreen`.
Тогда не нужно будет передавать setFullscreen, типизировать пропсы и т.д.
И вообще, логика будет вынесена в один хук.

2023-06-22 11:26 UTC, timerbayevaf commented on packages/client/src/store/slices/config-slice.ts
> +    initialTheme: state => {
а причем тут тема?

2023-06-22 13:10 UTC, closed without merging