Add Forum Pages, Boundary Error Children Component
FridayRelease/1game pull request #9
Opened 2023-03-31 08:30 UTC by Dmitryra27

### Какую задачу решаем
Создали страницы Форума и сделали Обработку ошибок детей в элементах React

### Скриншоты/видяшка (если есть)
![forum_1](https://user-images.githubusercontent.com/34819049/229499521-24bdd1d6-2e0c-4b20-9684-8eb6ef7c7984.png)
![forum_2](https://user-images.githubusercontent.com/34819049/229499539-9d5eb235-cb7e-496f-a000-f741e9574a4f.png)

### TBD (если есть)

2023-03-31 08:50 UTC, vvozvv commented on packages/client/src/features/forum/components/forum-comp.scss
> +  font-family: Inter, sans-serif;
шрифт - у нас константа  --main-font-family: 'Inter', sans-serif; в packages/client/src/app.scss лежит

2023-03-31 08:50 UTC, vvozvv commented on packages/client/src/features/forum/components/forum-comp.tsx
> +      onClick={() => navigate(`/forum/${chatId}`)}>
Предлагаю js выносить из jsx
Сделать отдельно функцию. Например goForum = () => navigate(`/forum/${chatId}`);

И уже в jsx передавать функцию 
onClick={goForum}

2023-03-31 08:50 UTC, vvozvv commented on packages/client/src/features/forum/components/forum-comp.tsx
> +function ForumComp(mess: forumMessage) {
Также предлагаю использовать jsdoc и подписывать компоненты/страницы. Forum-comp - малоинформативно 

/**
 * Страница форума
 *
 * @category page
 */
 
 Смотрится понятнее и меньше вопросов. В теориях яндекса даже такое встречалось - " однако дальше будем в основном придерживаться принципа: «Явное — лучше неявного»." :)

2023-03-31 08:50 UTC, vvozvv commented on packages/client/src/features/forum/forum.scss
> +}
.red, .white 
похоже на глобальный стили, которые могут использовать вне страницы форму
может их вынести в app.scss?

2023-03-31 08:50 UTC, vvozvv commented on packages/client/src/assets/images/create.png
Лучше наверное svg иконки подключить

2023-04-03 11:58 UTC, shoom1337-yt requested changes

2023-04-03 11:58 UTC, shoom1337-yt commented on packages/client/src/assets/images/create.png
❓ Вроде заменили на svg? Удалить нужно?

2023-04-03 11:58 UTC, shoom1337-yt commented on packages/client/src/components/button-new/button-new.scss
ℹ️ Если не понадобится, то нужно удалить.

2023-04-03 11:58 UTC, shoom1337-yt commented on packages/client/src/features/forum-user/components/forum-user-comp.scss
> +  font-family: Inter, sans-serif;
❓ Повторяется третий раз в одном файле. Точно в переменные.

2023-04-03 11:58 UTC, shoom1337-yt commented on packages/client/src/features/forum-user/forum-user.scss
> +  padding: 10px 10px 10px 10px;
ℹ️ Можно так:
```
margin: 10px;
padding: 10px;
```
Получится короче 🙂

2023-04-03 19:13 UTC, Dmitryra27 commented on packages/client/src/assets/images/create.png
удалил

2023-04-03 19:13 UTC, Dmitryra27 commented on packages/client/src/components/button-new/button-new.scss
удалил

2023-04-03 19:19 UTC, Dmitryra27 commented on packages/client/src/features/forum-user/forum-user.scss
> +  padding: 10px 10px 10px 10px;
исправил

2023-04-03 19:19 UTC, Dmitryra27 commented on packages/client/src/features/forum-user/components/forum-user-comp.scss
> +  font-family: Inter, sans-serif;
исправил

2023-04-03 19:19 UTC, Dmitryra27 commented on packages/client/src/features/forum-user/components/forum-user-comp.scss
> +  color: #757575;
исправил

2023-04-03 19:23 UTC, Dmitryra27 commented on packages/client/src/features/forum-user/forum-user.scss
> +  font-family: Joystix, sans-serif;
исправил

2023-04-03 19:24 UTC, Dmitryra27 commented on packages/client/src/features/forum-user/forum-user.tsx
> +  ));
Я ранее сделал компонент ForumUserComp - я логику отрисовки в цикле оставил в forum-user.tsx

2023-04-03 19:35 UTC, Dmitryra27 commented on packages/client/src/features/forum-user/forum-user.tsx
> +  ));
Подскажите, какой компонент лучше сделать - я не сообразил сразу, - с удовольствием научусь и переделаю.

2023-04-04 06:56 UTC, shoom1337-yt commented on packages/client/src/features/forum-user/forum-user.tsx
> +  ));
Я за подход "не хранить разметку в переменных". 
Исходя из использования `<div className="forum-user-messages column">{listItems}</div>`, вижу, что это список сообщений.
Я бы вынес `listItems` в компонент, например, `MessagesList`. И потом использовал так:
```<div className="forum-user-messages column">
  <MessagesList messages="result" />
</div>```

2023-04-04 06:58 UTC, shoom1337-yt approved these changes

2023-04-04 11:26 UTC, merged